import Foundation

/// Turning a signed invitation into something a person can send, and back.
///
/// `AdminApi` already mints invitations (`createNamespaceInvitation`) and
/// redeems them (`joinNamespace`). What was missing is the bit in between: the
/// wire format the rest of the Calimero apps share, so an invitation created on
/// a phone can be redeemed by the desktop or the web build, and vice versa.
///
/// The format is `base58(deflate(JSON))`, which is what mero-blocks, merraria,
/// mero-stream, mero-chat, mero-design, mero-pixart, mero-calendar and mero-meet
/// all emit. Compression is not cosmetic: the payload is JSON carrying 32-byte
/// arrays rendered as decimal numbers, so it is enormously redundant. For a real
/// invitation, plain base64url produces a ~930-character link and this produces
/// ~540.
///
/// **On the deflate flavour.** `NSData.compressed(using: .zlib)` is *raw*
/// DEFLATE (RFC 1951) with no zlib header, which is the same thing the JS side's
/// `fflate.deflateSync` produces. Verified both directions against the JS
/// implementation — see `InviteCodecTests`, which carries a token generated by
/// `bs58` + `fflate` as a fixture. The two compressors do not emit identical
/// bytes for the same input (Apple's and fflate's choices differ), and they do
/// not need to: each side inflates the other's output exactly.
public enum InviteCodec {

    // MARK: Base58

    private static let alphabet = Array("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz")
    private static let index: [Character: Int] = {
        var map = [Character: Int]()
        for (i, c) in alphabet.enumerated() { map[c] = i }
        return map
    }()

    /// Base58 (bitcoin alphabet), byte-compatible with the JS `bs58` package.
    public static func base58Encode(_ data: Data) -> String {
        guard !data.isEmpty else { return "" }
        var digits = [0]
        for byte in data {
            var carry = Int(byte)
            for i in 0..<digits.count {
                carry += digits[i] << 8
                digits[i] = carry % 58
                carry /= 58
            }
            while carry > 0 {
                digits.append(carry % 58)
                carry /= 58
            }
        }
        var out = ""
        // Leading zero bytes are encoded as leading '1's, not as digits.
        for byte in data {
            if byte == 0 { out.append(alphabet[0]) } else { break }
        }
        for digit in digits.reversed() { out.append(alphabet[digit]) }
        return out
    }

    /// Returns nil for any character outside the base58 alphabet.
    public static func base58Decode(_ string: String) -> Data? {
        guard !string.isEmpty else { return Data() }
        var bytes = [0]
        for character in string {
            guard let value = index[character] else { return nil }
            var carry = value
            for i in 0..<bytes.count {
                carry += bytes[i] * 58
                bytes[i] = carry & 0xff
                carry >>= 8
            }
            while carry > 0 {
                bytes.append(carry & 0xff)
                carry >>= 8
            }
        }
        var leadingZeros = 0
        for character in string {
            if character == alphabet[0] { leadingZeros += 1 } else { break }
        }
        return Data(repeating: 0, count: leadingZeros)
            + Data(bytes.reversed().map { UInt8($0) })
    }

    // MARK: Raw DEFLATE

    static func deflate(_ data: Data) -> Data? {
        try? (data as NSData).compressed(using: .zlib) as Data
    }

    static func inflate(_ data: Data) -> Data? {
        try? (data as NSData).decompressed(using: .zlib) as Data
    }

    // MARK: The codec

    /// Compress and base58-encode a JSON string into the shareable token.
    public static func encode(json: String) -> String? {
        guard let compressed = deflate(Data(json.utf8)) else { return nil }
        return base58Encode(compressed)
    }

    /// Decode any form a Calimero app has ever emitted, back to the JSON string:
    ///
    /// 1. `base58(deflate(JSON))` — what ``encode(json:)`` produces
    /// 2. `base58(JSON)` — uncompressed, from older clients
    /// 3. `base64url(JSON)` — what several web apps emitted before compressing
    /// 4. raw JSON — hand-assembled, and useful when debugging
    ///
    /// base58 is attempted first because the two alphabets overlap: a short
    /// string can be valid in both and only one reading is right. Every branch
    /// additionally requires the result to *look* like JSON before accepting it —
    /// without that, a short base58 string decodes to arbitrary bytes and the
    /// caller gets mojibake instead of a clear failure.
    ///
    /// Returns nil when nothing decodes, so a malformed invitation fails loudly
    /// rather than reaching `JSONDecoder` as garbage.
    public static func decode(token: String) -> String? {
        let trimmed = token.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        if looksLikeJSON(trimmed) { return trimmed }

        if let raw = base58Decode(trimmed) {
            if let inflated = inflate(raw), let text = utf8JSON(inflated) { return text }
            if let text = utf8JSON(raw) { return text }
        }

        if let data = base64URLDecode(trimmed), let text = utf8JSON(data) { return text }

        return nil
    }

    /// Encode any `Encodable` payload as a shareable token.
    public static func encode<T: Encodable>(_ value: T) throws -> String {
        let encoder = JSONEncoder()
        // Stable key order keeps the token deterministic across runs, which
        // makes it diffable in tests and in logs.
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(value)
        guard let json = String(data: data, encoding: .utf8), let token = encode(json: json) else {
            throw MeroError.decoding("could not encode invitation payload")
        }
        return token
    }

    /// Decode a token into a `Decodable` payload.
    public static func decode<T: Decodable>(_ type: T.Type, from token: String) throws -> T {
        guard let json = decode(token: token), let data = json.data(using: .utf8) else {
            throw MeroError.decoding("not a recognizable invitation token")
        }
        return try JSONDecoder().decode(type, from: data)
    }

    // MARK: Helpers

    private static func looksLikeJSON(_ s: String) -> Bool {
        s.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("{")
    }

    private static func utf8JSON(_ data: Data) -> String? {
        guard let text = String(data: data, encoding: .utf8), looksLikeJSON(text) else { return nil }
        return text
    }

    private static func base64URLDecode(_ s: String) -> Data? {
        var padded = s.replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        let remainder = padded.count % 4
        if remainder != 0 { padded += String(repeating: "=", count: 4 - remainder) }
        return Data(base64Encoded: padded)
    }
}
