import XCTest

@testable import MeroKit

/// The invitation wire format, and its compatibility with the JavaScript apps.
///
/// The fixture below was generated by the real JS libraries (`bs58` +
/// `fflate.deflateSync`, level 9) that every web and desktop Calimero app uses.
/// If a change here stops decoding it, invitations sent from a web app stop
/// working on iOS — which is a silent, user-visible break, so it is pinned.
final class InviteCodecTests: XCTestCase {

    /// base58(deflate(JSON)) produced by bs58 + fflate.
    private let jsToken = "T3MBR42kMWfzJn5wMvCqe1r7c1hYDuexnUKzqjSNCtW4k71PM1Jkbton9UzSky4P3Vu2kz8bft3hcchY2HESbzeq4WbgLAjTJs6Ep9vxyp5hCD3s9geS6EjLnBnDAQ5Lr2CjSQxB5h7vQmGu11ARv7ty7YAtw"
    private let jsJSON = #"{"__teamName":"Design Team","invitation":{"invitation":{"expires_at":1787740000000,"group_id":[13,20,27,34,41,48]},"inviter_signature":"5555"}}"#

    // MARK: Cross-language compatibility

    func testDecodesATokenProducedByTheJavaScriptApps() {
        XCTAssertEqual(InviteCodec.decode(token: jsToken), jsJSON)
    }

    func testOurOwnTokenDecodesBackToTheSameJSON() {
        // Note: our compressor and fflate do NOT emit identical bytes for the
        // same input, so the tokens differ. What must hold is that each side
        // inflates the other's output — the JS direction is covered by a test in
        // the web repos against a Swift-produced token.
        guard let ours = InviteCodec.encode(json: jsJSON) else {
            return XCTFail("encode returned nil")
        }
        XCTAssertEqual(InviteCodec.decode(token: ours), jsJSON)
    }

    // MARK: Round-trips

    func testRoundTripsNonASCIIText() {
        let json = #"{"__teamName":"Café — 東京 🎨"}"#
        let token = InviteCodec.encode(json: json)
        XCTAssertNotNil(token)
        XCTAssertEqual(InviteCodec.decode(token: token!), json)
    }

    func testRoundTripsACodableInvitation() throws {
        let signed = SignedGroupOpenInvitation(
            invitation: GroupInvitationFromAdmin(
                inviterIdentity: Array(0..<32),
                groupId: Array(32..<64),
                expirationTimestamp: 1_787_740_000_000,
                secretSalt: Array(64..<96)
            ),
            inviterSignature: String(repeating: "5", count: 88)
        )
        let token = try InviteCodec.encode(signed)
        let back = try InviteCodec.decode(SignedGroupOpenInvitation.self, from: token)
        XCTAssertEqual(back.inviterSignature, signed.inviterSignature)
        XCTAssertEqual(back.invitation.groupId, signed.invitation.groupId)
    }

    func testCompressionIsWorthIt() throws {
        let signed = SignedGroupOpenInvitation(
            invitation: GroupInvitationFromAdmin(
                inviterIdentity: Array(0..<32),
                groupId: Array(32..<64),
                expirationTimestamp: 1_787_740_000_000,
                secretSalt: Array(64..<96)
            ),
            inviterSignature: String(repeating: "5", count: 88)
        )
        let compressed = try InviteCodec.encode(signed)
        let uncompressed = try JSONEncoder().encode(signed).base64EncodedString()
        // Measured roughly 45% of the base64 form for a real invitation.
        XCTAssertLessThan(compressed.count, Int(Double(uncompressed.count) * 0.7))
    }

    // MARK: Backward and defensive behaviour

    func testDecodesTheLegacyBase64URLForm() {
        let json = #"{"invitation":{"group_id":"abc"}}"#
        var b64 = Data(json.utf8).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
        while b64.hasSuffix("=") { b64.removeLast() }
        XCTAssertEqual(InviteCodec.decode(token: b64), json)
    }

    func testDecodesUncompressedBase58() {
        let json = #"{"invitation":{"group_id":"abc"}}"#
        let token = InviteCodec.base58Encode(Data(json.utf8))
        XCTAssertEqual(InviteCodec.decode(token: token), json)
    }

    func testDecodesRawJSON() {
        let json = #"{"a":1}"#
        XCTAssertEqual(InviteCodec.decode(token: json), json)
    }

    func testRejectsAShortAmbiguousStringRatherThanReturningMojibake() {
        // "YQ" is valid base58 AND valid base64url; neither reading is JSON.
        // Guessing would hand the caller two arbitrary bytes.
        XCTAssertNil(InviteCodec.decode(token: "YQ"))
        XCTAssertNil(InviteCodec.decode(token: "YWI"))
        XCTAssertNil(InviteCodec.decode(token: "not an invitation"))
        XCTAssertNil(InviteCodec.decode(token: "   "))
    }

    func testBase58RejectsCharactersOutsideTheAlphabet() {
        // 0, O, I and l are deliberately absent from base58.
        XCTAssertNil(InviteCodec.base58Decode("0OIl"))
    }

    func testBase58PreservesLeadingZeroBytes() {
        let data = Data([0, 0, 1, 2, 3])
        let encoded = InviteCodec.base58Encode(data)
        XCTAssertTrue(encoded.hasPrefix("11"))
        XCTAssertEqual(InviteCodec.base58Decode(encoded), data)
    }
}
